name: travaly
description: "Screening Task for MyTravaly"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  google_sign_in: ^7.2.0
  google_fonts: ^6.3.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.9.0
  device_info_plus: ^12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true